name: Build TWRP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout device tree
        uses: actions/checkout@v4

      - name: Mostrar archivos
        run: |
          pwd
          ls -R
